Fix yaml linter errors with line length on regression.yml

diff --git a/.github/workflows/regression.yml b/.github/workflows/regression.yml
--- a/.github/workflows/regression.yml
+++ b/.github/workflows/regression.yml
@@ -1,5 +1,6 @@
 ---
 name: Regression Testing
+
 on:
   push:
     branches:
@@ -19,6 +20,7 @@ on:
 defaults:
   run:
     working-directory: ./playwright
+
 jobs:
   test_staging:
     runs-on: ubuntu-latest
@@ -42,21 +44,20 @@ jobs:
           PW_XFD_PASSWORD: ${{ secrets.PW_XFD_PASSWORD }}
           PW_XFD_USERNAME: ${{ secrets.PW_XFD_USERNAME }}
         run: |
-         aws ecs run-task \
-         --cluster crossfeed-playwright-staging-ecs-cluster \
-         --task-definition playwright \
-         --launch-type FARGATE \
-         --network-configuration "awsvpcConfiguration=\
-          {subnets=['${{ secrets.AWS_SUBNET}}'], \
-          securityGroups=['${{ secrets.AWS_SECURITY_GROUP}}'],\
-          assignPublicIp='ENABLED'}" \
-         --overrides '{
-         "containerOverrides": [
-          {
-            "name": "playwright",
-            "command": ["npx", "playwright", "test"]
-          }
-          ]}'
+          aws ecs run-task \
+            --cluster crossfeed-playwright-staging-ecs-cluster \
+            --task-definition playwright \
+            --launch-type FARGATE \
+            --network-configuration \
+            "awsvpcConfiguration={subnets=[\"${{ secrets.AWS_SUBNET }}\"], \
+            securityGroups=[\"${{ secrets.AWS_SECURITY_GROUP }}\"], \
+            assignPublicIp=\"ENABLED\"}" \
+            --overrides '{\
+            "containerOverrides":[{\
+            "name":"playwright",\
+            "command"\
+            ["npx","playwright","test"]}]}'
+        continue-on-error: false  # Ensure it stops if the ECS task fails
 
       - name: Upload test results as artifact
         uses: actions/upload-artifact@v2
@@ -65,22 +66,21 @@ jobs:
           path: ./test-results/*.json
 
       - name: Upload HTML report to S3
-        run: >
-          aws s3 cp ./playwright-report/html
-            s3://${{ vars.AUTOMATED_TEST_REPORT_BUCKET_NAME }}
-            /playwright-reports/html/
-            --recursive ||
-            { echo "HTML report upload failed"; exit 1; }
+        run: |
+          aws s3 cp ./playwright-report/html \
+            s3://${{ vars.AUTOMATED_TEST_REPORT_BUCKET_NAME }}/\
+            playwright-reports/html/ --recursive || \
+          { echo "HTML report upload failed"; exit 1; }
 
       - name: Upload JSON report to S3
-        run: >
-          if aws s3 cp ./playwright-report/results.json
-            s3://${{ vars.AUTOMATED_TEST_REPORT_BUCKET_NAME }}
-            /playwright-reports/results.json;
-             then echo "JSON report uploaded successfully."
-          else
-            echo "Failed to upload JSON report to S3." >&2
-            exit 1
+        run: |
+          if aws s3 cp ./playwright-report/results.json \
+            s3://${{ vars.AUTOMATED_TEST_REPORT_BUCKET_NAME }}/\
+            playwright-reports/results.json; then \
+            echo "JSON report uploaded successfully."; \
+          else \
+            echo "Failed to upload JSON report to S3." >&2; \
+            exit 1; \
           fi
 
   test_integration:
@@ -105,21 +105,19 @@ jobs:
           PW_XFD_PASSWORD: ${{ secrets.PW_XFD_PASSWORD }}
           PW_XFD_USERNAME: ${{ secrets.PW_XFD_USERNAME }}
         run: |
-         aws ecs run-task \
-         --cluster crossfeed-playwright-integration-ecs-cluster \
-         --task-definition playwright \
-         --launch-type FARGATE \
-         --network-configuration "awsvpcConfiguration=\
-          {subnets=['${{ secrets.AWS_SUBNET}}'], \
-          securityGroups=['${{ secrets.AWS_SECURITY_GROUP}}'],\
-          assignPublicIp='ENABLED'}" \
-         --overrides '{
-         "containerOverrides": [
-          {
-            "name": "playwright",
-            "command": ["npx", "playwright", "test"]
-          }
-          ]}'
+          aws ecs run-task \
+            --cluster crossfeed-playwright-integration-ecs-cluster \
+            --task-definition playwright \
+            --launch-type FARGATE \
+            --network-configuration \
+            "awsvpcConfiguration={subnets=[\"${{ secrets.AWS_SUBNET }}\"], \
+            securityGroups=[\"${{ secrets.AWS_SECURITY_GROUP }}\"], \
+            assignPublicIp=\"ENABLED\"}" \
+            --overrides '{"containerOverrides":\
+            [{"name":"playwright",\
+            "command":["npx",\
+            "playwright","test"]}]}'
+        continue-on-error: false  # Ensure it stops if the ECS task fails
 
       - name: Upload test results as artifact
         uses: actions/upload-artifact@v2
@@ -128,20 +126,19 @@ jobs:
           path: ./test-results/*.json
 
       - name: Upload HTML report to S3
-        run: >
-          aws s3 cp ./playwright-report/html
-            s3://${{ vars.AUTOMATED_TEST_REPORT_BUCKET_NAME }}
-            /playwright-reports/html/
-            --recursive ||
-            { echo "HTML report upload failed"; exit 1; }
+        run: |
+          aws s3 cp ./playwright-report/html \
+            s3://${{ vars.AUTOMATED_TEST_REPORT_BUCKET_NAME }}/\
+            playwright-reports/html/ --recursive || \
+          { echo "HTML report upload failed"; exit 1; }
 
       - name: Upload JSON report to S3
-        run: >
-          if aws s3 cp ./playwright-report/results.json
-            s3://${{ vars.AUTOMATED_TEST_REPORT_BUCKET_NAME }}
-            /playwright-reports/results.json;
-             then echo "JSON report uploaded successfully."
-          else
-            echo "Failed to upload JSON report to S3." >&2
-            exit 1
+        run: |
+          if aws s3 cp ./playwright-report/results.json \
+            s3://${{ vars.AUTOMATED_TEST_REPORT_BUCKET_NAME }}/\
+            playwright-reports/results.json; then \
+            echo "JSON report uploaded successfully."; \
+          else \
+            echo "Failed to upload JSON report to S3." >&2; \
+            exit 1; \
           fi
