Create separate jobs for playwright tests on develop, integration branches. Changes to Terraform for Playwright AWS.

diff --git a/.github/workflows/regression.yml b/.github/workflows/regression.yml
--- a/.github/workflows/regression.yml
+++ b/.github/workflows/regression.yml
@@ -1,92 +1,30 @@
 ---
 name: Regression Testing
 on:
-  deployment_status:
+  push:
+    branches:
+      - develop
+      - integration
+    paths:
+      - backend/**
+      - .github/workflows/backend.yml
+  pull_request:
+    branches:
+      - develop
+      - integration
+    paths:
+      - backend/**
+      - .github/workflows/backend.yml
 
 defaults:
   run:
     working-directory: ./playwright
 jobs:
-  build:
+  test_staging:
     runs-on: ubuntu-latest
-    if: ${{ github.event.deployment_status.state == 'success' }}
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
-
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v2
-
-      - name: Cache Docker layers
-        uses: actions/cache@v2
-        with:
-          path: /tmp/.buildx-cache
-          key: ${{ runner.os }}-buildx-${{ github.ref }}
-          restore-keys: |
-            ${{ runner.os }}-buildx-
-
-      - name: Build Docker image
-        run: |
-          docker build -t \
-          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.\
-          amazonaws.com/playwright-tests:latest .
-
-      - name: Build Docker services
-        run: docker-compose build
-
-      - name: Log in to Amazon ECR
-        uses: aws-actions/amazon-ecr-login@v1
-
-      - name: Push Docker image to ECR
-        run: >
-          export AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID }}
-          export AWS_REGION=${{ secrets.AWS_REGION }}
-          docker tag
-          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/playwright-tests:latest
-          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/playwright-tests:latest
-          docker push
-          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/playwright-tests:latest
-
-  deploy:
-    runs-on: ubuntu-latest
-    if: ${{ github.event.deployment_status.state == 'success' }}
-    needs: build
-    environment: ${{ github.event.deployment_status.environment }}
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
-
-      - name: Set up AWS CLI
-        uses: aws-actions/configure-aws-credentials@v1
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: ${{ secrets.AWS_REGION }}
-
-      - name: Deploy with ECS CLI
-        run: |
-          ecs-cli configure --region ${{ secrets.AWS_REGION }} \
-          --cluster playwright-cluster
-          ecs-cli compose --file docker-compose.yml \
-            --project-name playwright-tests up
-
-          # Optionally wait for Fargate service to stabilize
-          timeout 600 aws ecs wait services-stable \
-            --cluster playwright-cluster \
-            --services playwright-service || \
-            echo "Timeout reached while waiting for service to stabilize."
-
-  test:
-    runs-on: ubuntu-latest
-    if: ${{ github.event.deployment_status.state == 'success' }}
-    needs: deploy
     environment: staging
     timeout-minutes: 60
     steps:
-      - name: Set container image
-        run: echo "CONTAINER_IMAGE=${{ secrets.AWS_ACCOUNT_ID }}\
-          .dkr.ecr.${{ secrets.AWS_REGION }}\
-          .amazonaws.com/playwright-tests:latest" >> $GITHUB_ENV
       - uses: actions/checkout@v3
       - uses: actions/setup-node@v3
         with:
@@ -97,12 +35,28 @@ jobs:
 
       - name: Run Playwright tests
         env:
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           PW_XFD_2FA_ISSUER: ${{ secrets.PW_XFD_2FA_ISSUER }}
           PW_XFD_2FA_SECRET: ${{ secrets.PW_XFD_2FA_SECRET }}
           PW_XFD_PASSWORD: ${{ secrets.PW_XFD_PASSWORD }}
           PW_XFD_USERNAME: ${{ secrets.PW_XFD_USERNAME }}
         run: |
-         docker run --rm $CONTAINER_IMAGE npx playwright test
+         aws ecs run-task \
+         --cluster crossfeed-playwright-staging-ecs-cluster \
+         --task-definition playwright \
+         --launch-type FARGATE \
+         --network-configuration "awsvpcConfiguration=\
+          {subnets=['${{ secrets.AWS_SUBNET}}'], \
+          securityGroups=['${{ secrets.AWS_SECURITY_GROUP}}'],\
+          assignPublicIp='ENABLED'}" \
+         --overrides '{
+         "containerOverrides": [
+          {
+            "name": "playwright",
+            "command": ["npx", "playwright", "test"]
+          }
+          ]}'
 
       - name: Upload test results as artifact
         uses: actions/upload-artifact@v2
@@ -113,7 +67,7 @@ jobs:
       - name: Upload HTML report to S3
         run: >
           aws s3 cp ./playwright-report/html
-            s3://${{ secrets.AUTOMATED_TEST_REPORT_BUCKET_NAME }}
+            s3://${{ vars.AUTOMATED_TEST_REPORT_BUCKET_NAME }}
             /playwright-reports/html/
             --recursive ||
             { echo "HTML report upload failed"; exit 1; }
@@ -121,7 +75,70 @@ jobs:
       - name: Upload JSON report to S3
         run: >
           if aws s3 cp ./playwright-report/results.json
-            s3://${{ secrets.AUTOMATED_TEST_REPORT_BUCKET_NAME }}
+            s3://${{ vars.AUTOMATED_TEST_REPORT_BUCKET_NAME }}
+            /playwright-reports/results.json;
+             then echo "JSON report uploaded successfully."
+          else
+            echo "Failed to upload JSON report to S3." >&2
+            exit 1
+          fi
+
+  test_integration:
+    runs-on: ubuntu-latest
+    environment: integration
+    timeout-minutes: 60
+    steps:
+      - uses: actions/checkout@v3
+      - uses: actions/setup-node@v3
+        with:
+          node-version: 18
+
+      - name: Install dependencies
+        run: npm ci
+
+      - name: Run Playwright tests
+        env:
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          PW_XFD_2FA_ISSUER: ${{ secrets.PW_XFD_2FA_ISSUER }}
+          PW_XFD_2FA_SECRET: ${{ secrets.PW_XFD_2FA_SECRET }}
+          PW_XFD_PASSWORD: ${{ secrets.PW_XFD_PASSWORD }}
+          PW_XFD_USERNAME: ${{ secrets.PW_XFD_USERNAME }}
+        run: |
+         aws ecs run-task \
+         --cluster crossfeed-playwright-integration-ecs-cluster \
+         --task-definition playwright \
+         --launch-type FARGATE \
+         --network-configuration "awsvpcConfiguration=\
+          {subnets=['${{ secrets.AWS_SUBNET}}'], \
+          securityGroups=['${{ secrets.AWS_SECURITY_GROUP}}'],\
+          assignPublicIp='ENABLED'}" \
+         --overrides '{
+         "containerOverrides": [
+          {
+            "name": "playwright",
+            "command": ["npx", "playwright", "test"]
+          }
+          ]}'
+
+      - name: Upload test results as artifact
+        uses: actions/upload-artifact@v2
+        with:
+          name: playwright-test-results
+          path: ./test-results/*.json
+
+      - name: Upload HTML report to S3
+        run: >
+          aws s3 cp ./playwright-report/html
+            s3://${{ vars.AUTOMATED_TEST_REPORT_BUCKET_NAME }}
+            /playwright-reports/html/
+            --recursive ||
+            { echo "HTML report upload failed"; exit 1; }
+
+      - name: Upload JSON report to S3
+        run: >
+          if aws s3 cp ./playwright-report/results.json
+            s3://${{ vars.AUTOMATED_TEST_REPORT_BUCKET_NAME }}
             /playwright-reports/results.json;
              then echo "JSON report uploaded successfully."
           else
